#!/usr/bin/env python3
"""
Generate realistic dummy patient test data for ALL analyzed forms.

Dummy Patient: Rajesh Kumar Sharma
- Male, 45 years old, DOB: 15/03/1980
- Diagnosis: Acute Appendicitis
- Treatment: Surgical (Laparoscopic Appendectomy) + Medical + Investigation + ICU
- Admission: 15/03/2025 (Planned + Emergency both checked for testing)
- Past history: Hypertension (since 2020)
- All Yes/No checkboxes are BOTH set to True (to test all fields render)
- All treatment type checkboxes are ALL set to True (surgical, medical, investigation, etc.)
- All gender checkboxes are ALL set to True (to test all render)
"""

import json
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
ANALYZED_DIR = PROJECT_ROOT / "analyzed"
TEST_DATA_DIR = PROJECT_ROOT / "test_data"
TEST_DATA_DIR.mkdir(exist_ok=True)

# ── Core patient data (shared across all forms) ────────────────────────────
P = {
    # Patient identity
    "patient_name": "Rajesh Kumar Sharma",
    "patient_first_name": "Rajesh",
    "patient_middle_name": "Kumar",
    "patient_last_name": "Sharma",
    "patient_surname": "Sharma",
    "first_name": "Rajesh",
    "middle_name": "Kumar",
    "last_name": "Sharma",
    "name_surname": "Sharma",
    "name_firstname": "Rajesh",
    "name_middlename": "Kumar",

    # Gender - ALL checked to test all fields
    "gender_male": True,
    "gender_female": True,
    "gender_third": True,
    "gender_third_gender": True,
    "patient_gender_male": True,
    "patient_gender_female": True,
    "patient_gender_third": True,
    "patient_gender_third_gender": True,
    "insured_person_gender_male": True,
    "insured_person_gender_female": True,

    # Age & DOB
    "age_years": "45",
    "age_months": "06",
    "patient_age": "45",
    "patient_age_years": "45",
    "patient_age_months": "06",
    "patient_age_yy": "45",
    "patient_age_mm": "06",
    "age_yy": "45",
    "age_mm": "06",
    "date_of_birth": "15/03/1980",
    "patient_dob": "15/03/1980",
    "patient_date_of_birth": "15/03/1980",
    "insured_person_dob": "15/03/1980",
    "dob_dd": "15",
    "dob_mm": "03",
    "dob_yyyy": "1980",

    # Contact
    "patient_contact_number": "9876543210",
    "patient_contact_no": "9876543210",
    "patient_mobile_no": "9876543210",
    "attending_relative_contact_number": "9876543211",
    "attending_relative_contact_name": "Priya Sharma - 9876543211",
    "relative_contact_number": "9876543211",
    "patient_alternate_contact_no": "9876543211",

    # Insurance
    "insured_card_id_number": "TPA-2024-00456",
    "insured_card_id": "TPA-2024-00456",
    "insured_card_id_no": "TPA-2024-00456",
    "patient_insurer_id_card_no": "TPA-2024-00456",
    "insured_member_id_card_no": "TPA-2024-00456",
    "policy_number_corporate_name": "POL-2024-78901 / Infosys Ltd.",
    "policy_corporate_name": "POL-2024-78901 / Infosys Ltd.",
    "policy_no_corporate_name": "POL-2024-78901 / Infosys Ltd.",
    "policy_no": "POL-2024-78901",
    "policy_number_corporate": "POL-2024-78901 / Infosys Ltd.",
    "policy_corporate_number": "POL-2024-78901",
    "patient_policy_corporate_name": "POL-2024-78901 / Infosys Ltd.",
    "page1_policy_number_corporate_name": "POL-2024-78901 / Infosys Ltd.",
    "employee_id": "EMP-INF-45678",
    "patient_employee_id": "EMP-INF-45678",
    "company_name": "Infosys Ltd.",
    "corporate_policy_no": "POL-2024-78901",
    "corporate_policy_name": "Infosys Group Health Policy",
    "health_card_no": "TPA-2024-00456",

    # Other mediclaim - BOTH yes/no checked
    "other_mediclaim_yes": True,
    "other_mediclaim_no": True,
    "other_mediclaim_health_insurance_yes": True,
    "other_mediclaim_health_insurance_no": True,
    "other_med_claim_health_insurance_yes": True,
    "other_med_claim_health_insurance_no": True,
    "other_mediclaim_insurance_yes": True,
    "other_mediclaim_insurance_no": True,
    "other_mediclaim_covered_yes": True,
    "other_mediclaim_covered_no": True,
    "patient_other_mediclaim_yes": True,
    "patient_other_mediclaim_no": True,
    "patient_other_medical_claim_yes": True,
    "patient_other_medical_claim_no": True,
    "mediclaim_health_insurance_yes": True,
    "mediclaim_health_insurance_no": True,
    "page1_other_insurance_yes": True,
    "page1_other_insurance_no": True,
    "page1_other_mediclaim_yes": True,
    "page1_other_mediclaim_no": True,
    "other_mediclaim_company_name": "Star Health Insurance",
    "other_mediclaim_details": "Policy No. SH-2023-11223, Sum Insured Rs. 3,00,000",
    "other_insurance_company_name": "Star Health Insurance",
    "other_insurance_details": "Policy No. SH-2023-11223",
    "patient_other_mediclaim_company_name": "Star Health Insurance",
    "patient_other_mediclaim_details": "Policy No. SH-2023-11223",
    "other_mediclaim_company_name": "Star Health Insurance",
    "mediclaim_company_name": "Star Health Insurance",
    "mediclaim_details": "Policy No. SH-2023-11223",
    "other_company_name_details": "Star Health Insurance - Policy No. SH-2023-11223",
    "patient_other_insurer_name": "Star Health Insurance",
    "other_mediclaim_policy_no": "SH-2023-11223",
    "other_mediclaim_sum_insured": "3,00,000",
    "sum_insured": "3,00,000",
    "insurance_company_name": "Bajaj Allianz General Insurance",
    "other_insurance_policy_no": "SH-2023-11223",
    "cover_duration": "2 years",
    "j2_give_details": "Star Health Insurance - Policy No. SH-2023-11223, Sum Insured Rs. 3,00,000",

    # Family physician - BOTH yes/no checked
    "family_physician_yes": True,
    "family_physician_no": True,
    "has_family_physician_yes": True,
    "has_family_physician_no": True,
    "patient_family_physician_yes": True,
    "patient_family_physician_no": True,
    "page1_family_physician_yes": True,
    "page1_family_physician_no": True,
    "family_physician_name": "Dr. Suresh Mehta",
    "family_physician_contact_number": "9845001234",
    "family_physician_contact_no": "9845001234",
    "family_physician_contact": "9845001234",
    "family_physician_mobile_no": "9845001234",
    "patient_family_physician_name": "Dr. Suresh Mehta",
    "patient_family_physician_contact_no": "9845001234",
    "name_of_family_physician": "Dr. Suresh Mehta",
    "contact_number_if_any": "9845001234",
    "page1_family_physician_name": "Dr. Suresh Mehta",
    "page1_family_physician_contact": "9845001234",

    # Address & occupation
    "insured_patient_current_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "insured_patient_occupation": "Software Engineer",
    "patient_current_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "patient_occupation": "Software Engineer",
    "insured_current_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "insured_occupation": "Software Engineer",
    "insured_person_occupation_service": True,
    "insured_person_occupation_self_employed": True,
    "insured_person_occupation_homemaker": True,
    "insured_person_occupation_student": True,
    "insured_person_occupation_retired": True,
    "insured_person_occupation_other": True,
    "insured_person_occupation_other_specify": "Software Engineer",
    "occupation_of_insured_person": "Software Engineer",
    "patient_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "page1_insured_patient_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "page1_insured_patient_occupation": "Software Engineer",
    "insured_person_current_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "insured_person_address_line1": "42, MG Road, Koramangala",
    "insured_person_address_line2": "Bengaluru - 560034",
    "insured_person_city": "Bengaluru",
    "insured_person_state": "Karnataka",
    "insured_person_pin_code": "560034",
    "insured_person_phone_no": "9876543210",
    "insured_person_mobile_no": "9876543210",
    "insured_person_email_id": "rajesh.sharma@email.com",
    "insured_person_age": "45",

    # Hospital — Amrita Institute of Medical Sciences, Faridabad (hardcoded)
    "hospital_name": "Amrita Institute of Medical Sciences & Research Centre",
    "hospital_address": "Mata Amritanandamayi Marg, Sector-88, Faridabad",
    "hospital_rohini_id": "8900080528185",
    "hospital_email_id": "tpa@fbd.amrita.edu",
    "hospital_email": "tpa@fbd.amrita.edu",
    "hospital_id": "8900080528185",
    "hospital_fax_no": "0129-2280800",
    "hospital_phone_no": "0129-2280800",
    "hospital_contact_no": "0129-2280800",
    "hospital_location": "Sector-88, Faridabad, Haryana",
    "hospital_nt_code": "8900080528185",
    "rohin_id": "8900080528185",
    "page1_hospital_name": "Amrita Institute of Medical Sciences & Research Centre",
    "page1_hospital_address": "Mata Amritanandamayi Marg, Sector-88, Faridabad",
    "page1_hospital_rohini_id": "8900080528185",
    "page1_hospital_email": "tpa@fbd.amrita.edu",
    "hospital_name_admitted": "Amrita Institute of Medical Sciences & Research Centre",
    "hospital_details_name": "Amrita Institute of Medical Sciences & Research Centre",
    "hospital_details_id": "8900080528185",
    "hospital_type_network": True,
    "hospital_type_non_network": True,
    "non_network_hospital_address_line1": "Mata Amritanandamayi Marg",
    "non_network_hospital_address_line2": "Sector-88, Faridabad - 121002",
    "non_network_hospital_city": "Faridabad",
    "non_network_hospital_state": "Haryana",
    "non_network_hospital_pin_code": "121002",
    "non_network_hospital_phone_no": "0129-2280800",
    "non_network_hospital_registration_no_state_code": "HR-HOSP-2001-001",
    "non_network_hospital_pan": "AAAAI1234B",
    "non_network_hospital_inpatient_beds": "500",
    "non_network_hospital_ot_yes": True,
    "non_network_hospital_ot_no": True,
    "non_network_hospital_icu_yes": True,
    "non_network_hospital_icu_no": True,
    "non_network_hospital_others_facilities": "Cath Lab, NICU, PICU, Bone Marrow Transplant",

    # Provider (Bajaj style) — Amrita Faridabad
    "provider_hospital_name": "Amrita Institute of Medical Sciences & Research Centre",
    "provider_city_name": "Faridabad",
    "provider_pin_code": "121002",
    "provider_state_name": "Haryana",
    "provider_hosp_id": "8900080528185",
    "provider_landmark": "Sector-88, Near Amrita University",
    "provider_contact_no": "0129-2280800",
    "provider_fax_no": "0129-2280801",
    "provider_tpa_desk_no": "0129-2280802",
    "provider_email_id": "tpa@fbd.amrita.edu",

    # TPA
    "tpa_insurance_company_name": "Medi Assist TPA Pvt. Ltd.",
    "tpa_name": "Medi Assist TPA Pvt. Ltd.",
    "tpa_toll_free_phone_number": "1800-425-9449",
    "tpa_phone_number": "1800-425-9449",
    "tpa_toll_free_fax": "080-41432000",
    "tpa_fax": "080-41432000",
    "tpa_fax_email_id": "080-41432000 / support@mediassist.in",
    "toll_free_phone_number": "1800-425-9449",
    "toll_free_fax": "080-41432000",
    "page1_tpa_name": "Medi Assist TPA Pvt. Ltd.",
    "page1_tpa_phone_number": "1800-425-9449",
    "page1_tpa_fax": "080-41432000",
    "page1_insurance_company_name": "Bajaj Allianz General Insurance",

    # Treating doctor
    "treating_doctor_name": "Dr. Anand Krishnamurthy",
    "treating_doctor_contact_number": "9900112233",
    "treating_doctor_contact_no": "9900112233",
    "treating_doctor_mobile_no": "9900112233",
    "treating_doctor_name_p1": "Dr. Anand Krishnamurthy",
    "treating_doctor_contact_number_p1": "9900112233",
    "treating_doctor_name_1": "Dr. Anand Krishnamurthy",
    "treating_doctor_contact_number_1": "9900112233",
    "treating_doctor_name_2": "Dr. Anand Krishnamurthy",
    "doctor_name": "Dr. Anand Krishnamurthy",
    "doctor_contact_no": "9900112233",
    "name_of_treating_doctor": "Dr. Anand Krishnamurthy",
    "page1_treating_doctor_name": "Dr. Anand Krishnamurthy",
    "page1_treating_doctor_contact": "9900112233",
    "page2_treating_doctor_name": "Dr. Anand Krishnamurthy",
    "page2_treating_doctor_contact_number": "9900112233",
    "treating_doctor_surname": "Krishnamurthy",
    "treating_doctor_firstname": "Anand",
    "treating_doctor_middlename": "",

    # Illness / clinical
    "nature_of_illness_complaint": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "nature_of_illness_complaints": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "nature_of_illness_disease": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "illness_disease_complaint": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "illness_disease_presenting_complaints": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "illness_presenting_complaints": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "illness_disease_presenting_complaint": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "illness_nature_complaint": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "nature_of_illness_presenting_complaints": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "doctor_illness_nature": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "page2_illness_complaint": "Acute Appendicitis with severe right lower abdominal pain, nausea and fever",
    "page2_illness_complaint_line1": "Acute Appendicitis with severe right lower abdominal pain",
    "page2_illness_complaint_line2": "nausea, vomiting and fever since 3 days",
    "page2_illness_complaint_line3": "",

    "relevant_critical_findings": "RLQ tenderness, Rebound tenderness positive, WBC 14,500, USG shows inflamed appendix 9mm",
    "relevant_clinical_findings": "RLQ tenderness, Rebound tenderness positive, WBC 14,500, USG shows inflamed appendix 9mm",
    "critical_findings": "RLQ tenderness, Rebound tenderness positive, WBC 14,500, USG shows inflamed appendix 9mm",
    "doctor_clinical_findings": "RLQ tenderness, Rebound tenderness positive, WBC 14,500, USG shows inflamed appendix 9mm",
    "page2_critical_findings": "RLQ tenderness, Rebound tenderness positive, WBC 14,500, USG shows inflamed appendix 9mm",
    "page2_relevant_critical_findings_line1": "RLQ tenderness, Rebound tenderness positive",
    "page2_relevant_critical_findings_line2": "WBC 14,500, USG shows inflamed appendix 9mm",
    "page2_relevant_critical_findings_line3": "",

    "duration_of_ailment_days": "3",
    "duration_present_ailment_days": "3",
    "duration_of_present_ailment_days": "3",
    "ailment_duration_days": "3",
    "ailment_duration": "3 days",
    "ailment_duration_years": "0",
    "ailment_duration_months": "0",
    "duration_of_present_ailment_value": "3",
    "duration_of_present_ailment_unit": "Days",
    "doctor_ailment_duration_days": "3",
    "page2_ailment_duration_days": "3",
    "page2_ailment_duration": "3 days",

    "date_of_first_consultation": "12/03/2025",
    "date_first_consultation": "12/03/2025",
    "first_consultation_date": "12/03/2025",
    "doctor_first_consultation_date": "12/03/2025",
    "page2_first_consultation_date": "12/03/2025",
    "date_first_consultation_dd": "12",
    "date_first_consultation_mm": "03",
    "date_first_consultation_yy": "25",
    "first_consultation_date_d1": "1",
    "first_consultation_date_d2": "2",
    "first_consultation_date_m1": "0",
    "first_consultation_date_m2": "3",
    "first_consultation_date_y1": "2",
    "first_consultation_date_y2": "0",
    "first_consultation_date_y3": "2",
    "first_consultation_date_y4": "5",

    "past_history_of_ailment": "No significant past history. Mild hypertension since 2020.",
    "past_history_of_present_ailment": "No significant past history. Mild hypertension since 2020.",
    "past_history_present_ailment": "No significant past history. Mild hypertension since 2020.",
    "past_ailment_history": "No significant past history. Mild hypertension since 2020.",
    "doctor_past_ailment_history": "No significant past history. Mild hypertension since 2020.",
    "page2_past_ailment_history": "No significant past history. Mild hypertension since 2020.",
    "past_ailment_history": "No significant past history. Mild hypertension since 2020.",

    "provisional_diagnosis": "Acute Appendicitis",
    "doctor_provisional_diagnosis": "Acute Appendicitis",
    "page2_provisional_diagnosis": "Acute Appendicitis",

    "provisional_diagnosis_icd10_code": "K35.80",
    "icd_10_code": "K35.80",
    "icd10_code": "K35.80",
    "icd_10_codes": "K35.80",
    "icd10_code_diagnosis": "K35.80",
    "icd_10_code_diagnosis": "K35.80",
    "provisional_diagnosis_icd_code": "K35.80",
    "doctor_icd10_code": "K35.80",
    "treating_doctor_icd_10_code": "K35.80",
    "page2_icd10_code": "K35.80",
    "primary_diagnosis_icd10_code": "K35.80",
    "primary_diagnosis_description": "Acute Appendicitis",
    "additional_diagnosis_icd10_code": "I10",
    "additional_diagnosis_description": "Essential Hypertension",
    "comorbidities1_icd10_code": "I10",
    "comorbidities1_description": "Hypertension",
    "comorbidities2_icd10_code": "",
    "comorbidities2_description": "",
    "surgical_icd_10_code": "K35.80",

    # Treatment - ALL checked
    "treatment_medical_management": True,
    "treatment_surgical_management": True,
    "treatment_intensive_care": True,
    "treatment_investigation": True,
    "treatment_non_allopathic": True,
    "proposed_treatment_medical_management": True,
    "proposed_treatment_surgical_management": True,
    "proposed_treatment_intensive_care": True,
    "proposed_treatment_investigation": True,
    "proposed_treatment_non_allopathic": True,
    "proposed_treatment_intensivecare": True,
    "doctor_treatment_medical_management": True,
    "doctor_treatment_surgical_management": True,
    "doctor_treatment_intensive_care": True,
    "doctor_treatment_investigation": True,
    "doctor_treatment_non_allopathic": True,
    "treatment_medical": True,
    "treatment_surgical": True,
    "treatment_intensive": True,
    "investigation_checkbox": True,
    "non_allopathic_treatment_checkbox": True,
    "treatment_medical_management_select": "Medical Management",
    "treatment_surgical_management_select": "Surgical Management",
    "treatment_intensive_care_select": "Intensive Care",
    "treatment_investigation_select": "Investigation",
    "treatment_non_allopathic_select": "Non-allopathic treatment",
    "page2_treatment_medical_management": "Medical Management",
    "page2_treatment_surgical_management": "Surgical Management",
    "page2_treatment_intensive_care": "Intensive care",
    "page2_treatment_investigation": "Investigation",
    "page2_treatment_non_allopathic": "Non-allopathic treatment",
    "proposed_treatment_intensive_care_investigation": True,
    "proposed_treatment_non_allopathic": True,

    "investigation_medical_management_details": "CBC, LFT, RFT, USG Abdomen, Chest X-Ray, ECG, IV antibiotics (Cefoperazone + Metronidazole)",
    "doctor_investigation_management_details": "CBC, LFT, RFT, USG Abdomen, Chest X-Ray, ECG, IV antibiotics",
    "investigation_medical_management_details": "CBC, LFT, RFT, USG Abdomen, Chest X-Ray, ECG, IV antibiotics",
    "page2_investigation_medical_management_details": "CBC, LFT, RFT, USG Abdomen, Chest X-Ray, ECG",

    "route_of_drug_administration": "IV - Intravenous",
    "route_drug_administration": "IV - Intravenous",
    "drug_administration_route": "IV - Intravenous",
    "doctor_drug_administration_route": "IV - Intravenous",
    "page2_drug_administration_route": "IV - Intravenous",
    "drug_administration_iv": True,
    "drug_administration_oral": True,
    "drug_administration_other": True,

    "surgery_name": "Laparoscopic Appendectomy",
    "surgical_name_of_surgery": "Laparoscopic Appendectomy",
    "name_of_surgery": "Laparoscopic Appendectomy",
    "doctor_surgery_name": "Laparoscopic Appendectomy",
    "page2_surgical_name_of_surgery": "Laparoscopic Appendectomy",
    "surgical_name": "Laparoscopic Appendectomy",

    "surgical_icd10_pcs_code": "0DTJ4ZZ",
    "icd_10_pcs_code": "0DTJ4ZZ",
    "icd10_pcs_code": "0DTJ4ZZ",
    "icd10_pcs_code_surgery": "0DTJ4ZZ",
    "icd_10_pcs_code": "0DTJ4ZZ",
    "icd10pcs_code": "0DTJ4ZZ",
    "icd_pcs_code": "0DTJ4ZZ",
    "doctor_icd10_pcs_code": "0DTJ4ZZ",
    "treating_doctor_icd_10_pcs_code": "0DTJ4ZZ",
    "page2_icd10_pcs_code": "0DTJ4ZZ",
    "procedure1_icd10_pcs": "0DTJ4ZZ",
    "procedure1_description": "Laparoscopic Appendectomy",
    "procedure2_icd10_pcs": "",
    "procedure2_description": "",
    "procedure3_icd10_pcs": "",
    "procedure3_description": "",
    "details_of_procedure": "Laparoscopic Appendectomy under General Anesthesia",

    "other_treatment_details": "Pre-operative antibiotics, IV fluids, pain management, post-op care",
    "other_treatments_details": "Pre-operative antibiotics, IV fluids, pain management, post-op care",
    "doctor_other_treatments_details": "Pre-operative antibiotics, IV fluids, pain management",
    "page2_other_treatment_details": "Pre-operative antibiotics, IV fluids, pain management",

    # Anesthesia - ALL checked
    "anesthesia_type_local": True,
    "anesthesia_type_general": True,
    "anesthesia_type_regional": True,
    "anesthesia_type_dissociative": True,

    # Accident / injury - BOTH yes/no checked
    "how_injury_occurred": "N/A - Medical condition (Appendicitis)",
    "how_did_injury_occur": "N/A - Medical condition (Appendicitis)",
    "injury_cause": "N/A - Medical condition (Appendicitis)",
    "page2_how_injury_occurred": "N/A - Medical condition (Appendicitis)",

    "accident_is_rta_yes": True,
    "accident_is_rta_no": True,
    "rta_yes": True,
    "rta_no": True,
    "accident_rta_yes": True,
    "accident_rta_no": True,
    "is_rta_yes": True,
    "is_rta_no": True,
    "page2_accident_is_rta_yes": True,
    "page2_accident_is_rta_no": True,

    "accident_date_of_injury": "12/03/2025",
    "date_of_injury": "12/03/2025",
    "injury_date": "12/03/2025",
    "doctor_accident_date_of_injury": "12/03/2025",
    "page2_accident_date_of_injury": "12/03/2025",
    "date_of_injury_mm": "03",
    "date_of_injury_dd": "12",
    "date_of_injury_yyyy": "2025",
    "date_of_injury_d1": "1",
    "date_of_injury_d2": "2",
    "date_of_injury_m1": "0",
    "date_of_injury_m2": "3",
    "date_of_injury_y1": "2",
    "date_of_injury_y2": "0",
    "date_of_injury_y3": "2",
    "date_of_injury_y4": "5",

    "accident_report_to_police_yes": True,
    "accident_report_to_police_no": True,
    "accident_reported_to_police_yes": True,
    "accident_reported_to_police_no": True,
    "report_to_police_yes": True,
    "report_to_police_no": True,
    "reported_to_police_yes": True,
    "reported_to_police_no": True,
    "police_report_yes": True,
    "police_report_no": True,
    "doctor_accident_reported_police_yes": True,
    "doctor_accident_reported_police_no": True,
    "page2_accident_reports_to_police_yes": True,
    "page2_accident_reports_to_police_no": True,

    "accident_fir_no": "N/A",
    "fir_no": "N/A",
    "fir_mlc_no": "N/A",
    "doctor_accident_fir_no": "N/A",
    "page2_accident_fir_no": "N/A",
    "page2_accident_mlc_no": "N/A",

    "accident_substance_abuse_yes": True,
    "accident_substance_abuse_no": True,
    "substance_abuse_yes": True,
    "substance_abuse_no": True,
    "injury_substance_abuse_yes": True,
    "injury_substance_abuse_no": True,
    "injury_due_to_substance_abuse_yes": True,
    "injury_due_to_substance_abuse_no": True,
    "substance_alcohol_abuse_yes": True,
    "substance_alcohol_abuse_no": True,
    "doctor_substance_abuse_yes": True,
    "doctor_substance_abuse_no": True,
    "page2_accident_substance_abuse_yes": True,
    "page2_accident_substance_abuse_no": True,
    "injury_caused_by_substance_abuse_yes": True,
    "injury_caused_by_substance_abuse_no": True,
    "injury_disease_substance_abuse_yes": True,
    "injury_disease_substance_abuse_no": True,

    "accident_test_conducted_yes": True,
    "accident_test_conducted_no": True,
    "test_conducted_yes": True,
    "test_conducted_no": True,
    "test_conducted_to_establish_yes": True,
    "test_conducted_to_establish_no": True,
    "test_conducted_to_establish_this_yes": True,
    "test_conducted_to_establish_this_no": True,
    "test_to_establish_yes": True,
    "test_to_establish_no": True,
    "doctor_test_conducted_yes": True,
    "doctor_test_conducted_no": True,
    "page2_accident_test_conducted_yes": True,
    "page2_accident_test_conducted_no": True,
    "substance_abuse_test_conducted_yes": True,
    "substance_abuse_test_conducted_no": True,
    "test_conducted_substance_abuse_yes": True,
    "test_conducted_substance_abuse_no": True,
    "test_conducted_substance_abuse_no_attach_reports": True,

    # Injury cause checkboxes (HDGC style)
    "injury_cause_self_inflicted": True,
    "injury_cause_road_traffic_accident": True,
    "injury_cause_substance_abuse": True,
    "injury_cause_alcohol_consumption": True,
    "injury_cause_substance_abuse_alcohol_consumption": True,
    "hospitalized_last_four_years_yes": True,
    "hospitalized_last_four_years_no": True,
    "hospitalized_last_four_years_date": "N/A",
    "hospitalized_diagnosis": "N/A",
    "previously_covered_mediclaim_yes": True,
    "previously_covered_mediclaim_no": True,
    "previously_covered_company_name": "Star Health Insurance",
    "medico_legal_yes": True,
    "medico_legal_no": True,
    "medico_legal_yes_hospital": True,
    "medico_legal_no_hospital": True,
    "mlc_fir_attached_yes": True,
    "mlc_fir_attached_no": True,
    "reported_to_police_yes_hospital": True,
    "reported_to_police_no_hospital": True,
    "fir_no": "N/A",
    "not_reported_to_police_reasons": "N/A - Medical condition, not an accident",

    # Maternity - ALL checked (for testing)
    "maternity_g": True,
    "maternity_p": True,
    "maternity_l": True,
    "maternity_a": True,
    "maternity_gravida": True,
    "maternity_para": True,
    "maternity_living": True,
    "maternity_abortion": True,
    "doctor_maternity_g": True,
    "doctor_maternity_p": True,
    "doctor_maternity_l": True,
    "doctor_maternity_a": True,
    "page2_maternity_g": True,
    "page2_maternity_p": True,
    "page2_maternity_l": True,
    "page2_maternity_a": True,
    "maternity_expected_date_of_delivery": "N/A",
    "expected_date_of_delivery": "N/A",
    "expected_delivery_date": "N/A",
    "maternity_date_of_delivery": "N/A",
    "doctor_maternity_date_of_delivery": "N/A",
    "doctor_maternity_lmp": "N/A",
    "lmp_date": "N/A",
    "date_of_delivery": "N/A",
    "mode_of_delivery_vd": True,
    "mode_of_delivery_lscs": True,
    "maternity_gravida_status": "N/A",
    "maternity_date_of_delivery": "N/A",
    "page2_maternity_expected_delivery_date": "N/A",
    "expected_delivery_date_d1": "N",
    "expected_delivery_date_d2": "/",
    "expected_delivery_date_m1": "A",
    "expected_delivery_date_m2": "",
    "expected_delivery_date_y1": "",
    "expected_delivery_date_y2": "",
    "expected_delivery_date_y3": "",

    # Maternity text fields (HDFC/Health India style)
    "maternity_g_text": "2",
    "maternity_p_text": "1",
    "maternity_l_text": "1",
    "maternity_a_text": "0",

    # Admission
    "admission_date": "15/03/2025",
    "date_of_admission": "15/03/2025",
    "patient_admission_date": "15/03/2025",
    "expected_admission_date": "15/03/2025",
    "doctor_admission_date": "15/03/2025",
    "page2_admission_date": "15/03/2025",
    "page3_admission_date": "15/03/2025",
    "date_admission": "15/03/2025",
    "admission_date_d1": "1",
    "admission_date_d2": "5",
    "admission_date_m1": "0",
    "admission_date_m2": "3",
    "admission_date_y1": "2",
    "admission_date_y2": "0",
    "admission_date_y3": "2",
    "admission_date_y4": "5",

    "admission_time": "10:30",
    "time_of_admission": "10:30",
    "patient_admission_time": "10:30",
    "page2_admission_time": "10:30",
    "page3_admission_time": "10:30",
    "time_admission": "10:30",
    "admission_time_hh": "10",
    "admission_time_mm": "30",
    "time_of_admission_hh": "10",
    "time_of_admission_mm": "30",
    "time_admission_hh": "10",
    "time_admission_mm": "30",
    "admission_time_h1": "1",
    "admission_time_h2": "0",
    "admission_time_m1": "3",
    "admission_time_m2": "0",

    # Hospitalization type - BOTH checked
    "hospitalization_event_emergency": True,
    "hospitalization_event_planned": True,
    "hospitalization_emergency": True,
    "hospitalization_planned": True,
    "hospitalization_type_emergency": True,
    "hospitalization_type_planned": True,
    "admission_type_emergency": True,
    "admission_type_planned": True,
    "admission_type_daycare": True,
    "admission_type_maternity": True,
    "hospitalisation_event_emergency": True,
    "hospitalisation_event_planned": True,
    "page2_hospitalization_emergency": True,
    "page2_hospitalization_planned": True,
    "page3_hospitalization_event_emergency": True,
    "page3_hospitalization_event_planned": True,

    # Discharge
    "date_discharge": "20/03/2025",
    "patient_discharge_date": "20/03/2025",
    "time_discharge": "11:00",
    "patient_discharge_time": "11:00",
    "discharge_status_home": True,
    "discharge_status_another_hospital": True,
    "discharge_status_deceased": True,

    # Hospitalization due to
    "hospitalisation_due_to_illness": True,
    "hospitalisation_due_to_injury": True,
    "hospitalisation_due_to_maternity": True,
    "date_injury_disease_delivery": "12/03/2025",
    "date_admission": "15/03/2025",
    "time_admission": "10:30",
    "hospitalization_due_to_injury_yes": True,

    # Room category
    "room_category_daycare": True,
    "room_category_single_occupancy": True,
    "room_category_twin_sharing": True,
    "room_category_3_or_more_beds": True,

    # Relationship (HDGC)
    "relationship_self": True,
    "relationship_spouse": True,
    "relationship_child": True,
    "relationship_father": True,
    "relationship_mother": True,
    "relationship_other": True,
    "relationship_other_specify": "Self",

    # Past history / chronic illness - ALL conditions filled
    "past_history_diabetes": "No",
    "past_history_heart_disease": "No",
    "past_history_hypertension": "Yes - since 01/2020",
    "past_history_hyperlipidemias": "No",
    "past_history_osteoarthritis": "No",
    "past_history_asthma_copd_bronchitis": "No",
    "past_history_cancer": "No",
    "past_history_alcohol_drug_abuse": "No",
    "past_history_hiv_std_ailment": "No",
    "past_history_other_ailment_details": "Hypertension - controlled on Tab. Amlodipine 5mg OD",
    "chronic_illness_diabetes": "No",
    "chronic_illness_heart_disease": "No",
    "chronic_illness_hypertension": "Yes - since 01/2020",
    "chronic_illness_hyperlipidemias": "No",
    "chronic_illness_osteoarthritis": "No",
    "chronic_illness_asthma_copd_bronchitis": "No",
    "chronic_illness_cancer": "No",
    "chronic_illness_alcohol_drug_abuse": "No",
    "chronic_illness_hiv_std_ailment": "No",
    "chronic_illness_hiv_std": "No",
    "chronic_illness_other_ailment_details": "Hypertension - controlled on medication",
    "chronic_illness_other_details": "Hypertension - controlled on medication",
    "chronic_illness_since_month_year": "01/2020",
    "chronic_illness_since": "01/2020",
    "past_history_chronic_illness_since": "01/2020",
    "past_history_chronic_illness_since_month_year": "01/2020",
    "chronic_illness_since_month_year": "01/2020",
    "page3_past_history_diabetes": "No",
    "page3_past_history_heart_disease": "No",
    "page3_past_history_hypertension": "Yes - since 01/2020",
    "page3_past_history_hyperlipidemias": "No",
    "page3_past_history_osteoarthritis": "No",
    "page3_past_history_asthma_copd_bronchitis": "No",
    "page3_past_history_cancer": "No",
    "page3_past_history_alcohol_drug_abuse": "No",
    "page3_past_history_hiv_std_ailment": "No",
    "page3_past_history_other_ailment_details": "Hypertension - controlled on medication",

    # Chronic illness checkboxes (Bajaj / Care / ICICI / NIVA style)
    "history_diabetes_checkbox": True,
    "history_diabetes_date": "N/A",
    "history_heart_disease_checkbox": True,
    "history_heart_disease_date": "N/A",
    "history_hypertension_checkbox": True,
    "history_hypertension_date": "01/2020",
    "history_hyperlipidemia_checkbox": True,
    "history_hyperlipidemia_date": "N/A",
    "history_osteoarthritis_checkbox": True,
    "history_osteoarthritis_date": "N/A",
    "history_asthma_copd_bronchitis_checkbox": True,
    "history_asthma_copd_bronchitis_date": "N/A",
    "history_cancer_checkbox": True,
    "history_cancer_date": "N/A",
    "history_alcohol_drug_abuse_checkbox": True,
    "history_alcohol_drug_abuse_date": "N/A",
    "history_hiv_std_checkbox": True,
    "history_hiv_std_date": "N/A",
    "history_other_ailment_details": "Hypertension - controlled on Tab. Amlodipine 5mg OD since 2020",

    "past_history_diabetes_checkbox": True,
    "past_history_diabetes_since": "N/A",
    "past_history_diabetes_date": "N/A",
    "past_history_heart_disease_checkbox": True,
    "past_history_heart_disease_since": "N/A",
    "past_history_heart_disease_date": "N/A",
    "past_history_hypertension_checkbox": True,
    "past_history_hypertension_since": "01/2020",
    "past_history_hypertension_date": "01/2020",
    "past_history_hyperlipidemias_checkbox": True,
    "past_history_hyperlipidemias_since": "N/A",
    "past_history_hyperlipidemias_date": "N/A",
    "past_history_osteoarthritis_checkbox": True,
    "past_history_osteoarthritis_since": "N/A",
    "past_history_osteoarthritis_date": "N/A",
    "past_history_asthma_copd_bronchitis_checkbox": True,
    "past_history_asthma_copd_bronchitis_since": "N/A",
    "past_history_asthma_copd_bronchitis_date": "N/A",
    "past_history_cancer_checkbox": True,
    "past_history_cancer_since": "N/A",
    "past_history_cancer_date": "N/A",
    "past_history_alcohol_drug_abuse_checkbox": True,
    "past_history_alcohol_drug_abuse_since": "N/A",
    "past_history_alcohol_drug_abuse_date": "N/A",
    "past_history_hiv_std_related_ailments_checkbox": True,
    "past_history_hiv_std_related_ailments_since": "N/A",
    "past_history_hiv_std_related_ailments_date": "N/A",
    "past_history_any_other_ailment_checkbox": True,
    "past_history_any_other_ailment_details": "Hypertension - controlled on medication",
    "past_history_other_ailment_details_since": "N/A",
    "past_history_hiv_std_ailment_since": "N/A",

    "past_history_diabetes": True,
    "past_history_diabetes_since": "N/A",
    "past_history_heart_disease": True,
    "past_history_heart_disease_since": "N/A",
    "past_history_hypertension": True,
    "past_history_hypertension_since": "01/2020",
    "past_history_hyperlipidemias": True,
    "past_history_hyperlipidemias_since": "N/A",
    "past_history_osteoarthritis": True,
    "past_history_osteoarthritis_since": "N/A",
    "past_history_asthma_copd_bronchitis": True,
    "past_history_asthma_copd_bronchitis_since": "N/A",
    "past_history_cancer": True,
    "past_history_cancer_since": "N/A",
    "past_history_alcohol_drug_abuse": True,
    "past_history_alcohol_drug_abuse_since": "N/A",
    "past_history_hiv_std_ailments": True,
    "past_history_hiv_std_ailments_since": "N/A",
    "past_history_other_ailments": "Hypertension - controlled on medication",

    # Chronic illness date fields (Chola style)
    "chronic_illness_diabetes_since": "N/A",
    "chronic_illness_heart_disease_since": "N/A",
    "chronic_illness_hypertension_since": "01/2020",
    "chronic_illness_hyperlipidemias_since": "N/A",
    "chronic_illness_osteoarthritis_since": "N/A",
    "chronic_illness_asthma_copd_bronchitis_since": "N/A",
    "chronic_illness_cancer_since": "N/A",
    "chronic_illness_alcohol_drug_abuse_since": "N/A",
    "chronic_illness_hiv_std_related_ailments_since": "N/A",
    "chronic_illness_any_other_ailment_checkbox": True,
    "chronic_illness_any_other_ailment_details": "Hypertension",
    "chronic_illness_any_other_ailment_since": "01/2020",

    # NIVA-BUPA chronic illness checkboxes
    "chronic_illness_diabetes": True,
    "chronic_illness_diabetes_date": "N/A",
    "chronic_illness_heart_disease": True,
    "chronic_illness_heart_disease_date": "N/A",
    "chronic_illness_hypertension": True,
    "chronic_illness_hypertension_date": "01/2020",
    "chronic_illness_hyperlipidemias": True,
    "chronic_illness_hyperlipidemias_date": "N/A",
    "chronic_illness_osteoarthritis": True,
    "chronic_illness_osteoarthritis_date": "N/A",
    "chronic_illness_asthma_copd_bronchitis": True,
    "chronic_illness_asthma_copd_bronchitis_date": "N/A",
    "chronic_illness_cancer": True,
    "chronic_illness_cancer_date": "N/A",
    "chronic_illness_alcohol_drug_abuse": True,
    "chronic_illness_alcohol_drug_abuse_date": "N/A",
    "chronic_illness_hiv_std": True,
    "chronic_illness_hiv_std_date": "N/A",
    "related_ailment": "Hypertension",
    "any_other_ailment_details": "Hypertension - controlled on medication",

    # HDFC past history date fields
    "past_history_diabetes_date": "N/A",
    "past_history_heart_disease_date": "N/A",
    "past_history_hypertension_date": "01/2020",
    "past_history_hyperlipidemias_date": "N/A",
    "past_history_osteoarthritis_date": "N/A",
    "past_history_asthma_copd_bronchitis_date": "N/A",
    "past_history_cancer_date": "N/A",
    "past_history_alcohol_drug_abuse_date": "N/A",
    "past_history_hiv_std_related_ailments_date": "N/A",

    # Aditya Birla MM/YY style
    "past_history_diabetes_mm_yy": "N/A",
    "past_history_heart_disease_mm_yy": "N/A",
    "past_history_hypertension_mm_yy": "01/20",
    "past_history_hyperlipidemias_mm_yy": "N/A",
    "past_history_osteoarthritis_mm_yy": "N/A",
    "past_history_asthma_copd_bronchitis_mm_yy": "N/A",
    "past_history_cancer_mm_yy": "N/A",
    "past_history_alcohol_drug_abuse_mm_yy": "N/A",
    "past_history_any_hiv_std_related_ailment_mm_yy": "N/A",
    "past_history_any_other_ailment_details": "Hypertension - controlled on medication",

    # Future Generali style
    "hypertension_yes": True,
    "hypertension_no": True,
    "hypertension_duration": "5 years (since 2020)",
    "hyperlipidemia_yes": True,
    "hyperlipidemia_no": True,
    "hyperlipidemia_duration": "N/A",
    "cancer_yes": True,
    "cancer_no": True,
    "cancer_duration": "N/A",
    "osteoarthritis_yes": True,
    "osteoarthritis_no": True,
    "osteoarthritis_duration": "N/A",
    "diabetes_yes": True,
    "diabetes_no": True,
    "diabetes_duration": "N/A",
    "cardiovascular_diseases_yes": True,
    "cardiovascular_diseases_no": True,
    "cardiovascular_diseases_duration": "N/A",
    "asthma_copd_bronchitis_yes": True,
    "asthma_copd_bronchitis_no": True,
    "asthma_copd_bronchitis_duration": "N/A",
    "any_surgery_hospitalization_yes": True,
    "any_surgery_hospitalization_no": True,
    "any_surgery_hospitalization_duration": "N/A",
    "any_other_disease_disability_yes": True,
    "any_other_disease_disability_no": True,
    "any_other_disease_disability_duration": "N/A",
    "congenital_yes": True,
    "congenital_no": True,
    "congenital_internal_external": "N/A",
    "hiv_std_ailments_yes": True,
    "hiv_std_ailments_no": True,
    "hiv_std_ailments_duration": "N/A",
    "alcohol_drug_abuse_yes": True,
    "alcohol_drug_abuse_no": True,

    # Medi-assist digit-by-digit style
    "diabetes_checkbox": True,
    "diabetes_month_m1": "N",
    "diabetes_month_m2": "/",
    "diabetes_year_y1": "A",
    "heart_disease_checkbox": True,
    "heart_disease_month_m1": "N",
    "heart_disease_month_m2": "/",
    "heart_disease_year_y1": "A",
    "hypertension_checkbox": True,
    "hypertension_month_m1": "0",
    "hypertension_month_m2": "1",
    "hypertension_year_y1": "2020",
    "hyperlipidemias_checkbox": True,
    "hyperlipidemias_month_m1": "N",
    "hyperlipidemias_month_m2": "/",
    "hyperlipidemias_year_y1": "A",
    "osteoarthritis_checkbox": True,
    "osteoarthritis_month_m1": "N",
    "osteoarthritis_month_m2": "/",
    "osteoarthritis_year_y1": "A",
    "asthma_copd_bronchitis_checkbox": True,
    "asthma_copd_bronchitis_month_m1": "N",
    "asthma_copd_bronchitis_month_m2": "/",
    "asthma_copd_bronchitis_year_y1": "A",
    "cancer_checkbox": True,
    "cancer_month_m1": "N",
    "cancer_month_m2": "/",
    "cancer_year_y1": "A",
    "alcohol_drug_abuse_checkbox": True,
    "alcohol_drug_abuse_month_m1": "N",
    "alcohol_drug_abuse_month_m2": "/",
    "alcohol_drug_abuse_year_y1": "A",
    "hiv_std_related_ailments_checkbox": True,
    "hiv_std_related_ailments_month_m1": "N",
    "hiv_std_related_ailments_month_m2": "/",
    "hiv_std_related_ailments_year_y1": "A",
    "other_ailment_details": "Hypertension - controlled on medication",

    # Good Health MM/YY digit fields
    "illness_diabetes_checkbox": True,
    "illness_diabetes_mm": "N/A",
    "illness_diabetes_yy": "N/A",
    "illness_heart_disease_checkbox": True,
    "illness_heart_disease_mm": "N/A",
    "illness_heart_disease_yy": "N/A",
    "illness_hypertension_checkbox": True,
    "illness_hypertension_mm": "01",
    "illness_hypertension_yy": "20",
    "illness_hyperlipidemias_checkbox": True,
    "illness_hyperlipidemias_mm": "N/A",
    "illness_hyperlipidemias_yy": "N/A",
    "illness_osteoarthritis_checkbox": True,
    "illness_osteoarthritis_mm": "N/A",
    "illness_osteoarthritis_yy": "N/A",
    "illness_asthma_copd_bronchitis_checkbox": True,
    "illness_asthma_copd_bronchitis_mm": "N/A",
    "illness_asthma_copd_bronchitis_yy": "N/A",
    "illness_cancer_checkbox": True,
    "illness_cancer_mm": "N/A",
    "illness_cancer_yy": "N/A",
    "illness_alcohol_drug_abuse_checkbox": True,
    "illness_alcohol_drug_abuse_mm": "N/A",
    "illness_alcohol_drug_abuse_yy": "N/A",
    "illness_hiv_std_related_ailments_checkbox": True,
    "illness_hiv_std_related_ailments_mm": "N/A",
    "illness_hiv_std_related_ailments_yy": "N/A",
    "illness_any_other_ailment_details": "Hypertension - controlled on medication",

    # Med-Save page3 style
    "page3_past_history_diabetes_month_year": "N/A",
    "page3_past_history_heart_disease_month_year": "N/A",
    "page3_past_history_hypertension_month_year": "01/2020",
    "page3_past_history_hyperlipidemias_month_year": "N/A",
    "page3_past_history_osteoarthritis_month_year": "N/A",
    "page3_past_history_asthma_copd_bronchitis_month_year": "N/A",
    "page3_past_history_cancer_month_year": "N/A",
    "page3_past_history_alcohol_drug_abuse_month_year": "N/A",
    "page3_past_history_hiv_std_ailment_month_year": "N/A",
    "page3_past_history_other_ailment_details": "Hypertension - controlled on medication",

    # Expected stay & costs
    "expected_days_in_hospital": "5",
    "expected_days_stay_hospital": "5",
    "expected_days_stay_in_hospital": "5",
    "expected_hospital_stay_days": "5",
    "expected_hospital_days": "5",
    "expected_stay_days": "5",
    "expected_length_of_stay_days": "5",
    "page3_expected_days_in_hospital": "5",
    "page3_expected_days_stay_hospital": "5",

    "days_in_icu": "1",
    "icu_stay_days": "1",
    "expected_icu_days": "1",
    "page3_days_in_icu": "1",

    "room_type": "Twin Sharing",
    "class_of_accommodation": "Twin Sharing",
    "page3_room_type": "Twin Sharing",

    "per_day_room_rent_nursing_service_charges_patient_diet": "3500",
    "per_day_room_rent_nursing_diet": "3500",
    "per_day_room_rent_nursing_service_diet": "3500",
    "per_day_room_rent_charges": "3500",
    "per_day_room_rent_charges_diet": "3500",
    "room_rent_nursing_diet_cost": "3500",
    "room_rent_nursing_diet_amount": "3500",
    "per_day_room_rent_nursing_diet_rs": "3500",
    "cost_room_nursing_diet": "3500",
    "page3_per_day_room_rent_charges": "3500",
    "page3_per_day_room_rent_nursing_service_charges_patient_diet": "3500",

    "expected_cost_investigation_diagnostic": "8000",
    "expected_cost_investigation_diagnostics": "8000",
    "expected_cost_diagnosis_investigation": "8000",
    "cost_investigation_diagnostics": "8000",
    "investigation_diagnostics_cost": "8000",
    "investigations_diagnostics_amount": "8000",
    "expected_cost_investigation_diagnostics_rs": "8000",
    "page3_expected_cost_investigation_diagnostic": "8000",

    "icu_charges": "5000",
    "icu_charges_rs": "5000",
    "icu_charges_amount": "5000",
    "cost_icu_charges": "5000",
    "page3_icu_charges": "5000",

    "ot_charges": "25000",
    "ot_charges_rs": "25000",
    "operation_theatre_charges_amount": "25000",
    "cost_ot_charges": "25000",
    "page3_ot_charges": "25000",

    "professional_fees_surgeon_anesthetist_consultation": "15000",
    "professional_fees_charges": "15000",
    "professional_fees_surgeon_anaesthetist_consultation_charges_rs": "15000",
    "surgeon_anesthetist_consultation_fees": "15000",
    "surgeon_anesthetist_charges_amount": "15000",
    "doctor_consultant_visit_charges_amount": "2000",
    "cost_professional_fees": "15000",
    "page3_professional_fees_charges": "15000",

    "medicines_consumables_cost_of_implants": "10000",
    "medicines_consumables_implants_cost": "10000",
    "medicines_consumables_implants_other_expenses": "10000",
    "medicines_consumables_implants_other_hospital_expenses_rs": "10000",
    "medicines_consumables_amount": "10000",
    "implant_charges_amount": "0",
    "cost_medicines_consumables_implants": "10000",
    "medicines_consumables_implants": "10000",
    "page3_medicines_consumables_implants_cost": "10000",
    "page3_medicines_consumables_implants_line1": "Medicines Rs. 7000",
    "page3_medicines_consumables_implants_line2": "Consumables Rs. 3000",

    "other_hospital_expenses": "3000",
    "cost_other_hospital_expenses": "3000",
    "page3_other_hospital_expenses": "3000",

    "all_inclusive_package_charges": "0",
    "cost_all_inclusive_package": "0",
    "package_charges_amount": "0",
    "page3_all_inclusive_package_charges": "0",

    "sum_total_expected_cost_of_hospitalization": "84500",
    "sum_total_expected_cost_hospitalization": "84500",
    "total_expected_hospitalization_cost": "84500",
    "total_expected_cost_hospitalization": "84500",
    "total_estimated_expenses_amount": "84500",
    "total_expenses": "84500",
    "total_claimed_amount": "84500",
    "cost_total_expected_hospitalization": "84500",
    "page3_sum_total_expected_cost_hospitalization": "84500",
    "miscellaneous_amount": "3000",
    "equipment_monitor_amount": "2500",

    # Pre/post hospitalization
    "pre_hospitalization_expenses": "2000",
    "hospitalization_expenses": "84500",
    "post_hospitalization_expenses": "5000",
    "health_check_up_cost": "0",
    "ambulance_charges": "500",
    "others_expenses_code": "0",
    "pre_hospitalization_period_days": "3",
    "post_hospitalization_period_days": "7",
    "domiciliary_hospitalization_yes": True,
    "domiciliary_hospitalization_no": True,
    "hospital_daily_cash": "0",
    "surgical_cash": "0",
    "critical_illness_benefit": "0",
    "convalescence_benefit": "0",
    "pre_post_hospitalization_lump_sum_benefit": "0",
    "others_lump_sum_benefit": "0",
    "total_lump_sum_benefit": "0",

    # Pre-authorization
    "pre_authorization_obtained_yes": True,
    "pre_authorization_obtained_no": True,
    "pre_authorization_number": "PREAUTH-2025-001234",
    "pre_authorization_reason_not_obtained": "N/A",

    # System of medicine
    "system_of_medicine": "Allopathic",

    # Declaration - doctor
    "declaration_treating_doctor_name": "Dr. Anand Krishnamurthy",
    "declaration_treating_doctor_qualification": "MS (General Surgery)",
    "declaration_treating_doctor_registration_number": "KMC-12345/KA",
    "declaration_treating_doctor_registration_no": "KMC-12345/KA",
    "declaration_treating_doctor_registration_no_state_code": "KMC-12345/KA",
    "declaration_doctor_name": "Dr. Anand Krishnamurthy",
    "declaration_doctor_qualification": "MS (General Surgery)",
    "declaration_doctor_registration_no": "KMC-12345/KA",
    "declaration_doctor_surname": "Krishnamurthy",
    "declaration_doctor_first_name": "Anand",
    "declaration_doctor_middle_name": "",
    "declaration_qualification": "MS (General Surgery)",
    "declaration_registration_no_state_code": "KMC-12345/KA",
    "declaration_registration_number_state_code": "KMC-12345/KA",
    "treating_doctor_name_declaration": "Dr. Anand Krishnamurthy",
    "treating_doctor_qualification": "MS (General Surgery)",
    "treating_doctor_registration_no_state_code": "KMC-12345/KA",
    "treating_doctor_registration_no": "KMC-12345/KA",
    "treating_doctor_state_code": "KA",
    "mci_registration_no_state_code": "KMC-12345/KA",
    "doctor_qualification": "MS (General Surgery)",
    "doctor_registration_no_state_code": "KMC-12345/KA",
    "doctor_phone_no": "9900112233",
    "page3_declaration_treating_doctor_name": "Dr. Anand Krishnamurthy",
    "page3_declaration_treating_doctor_qualification": "MS (General Surgery)",
    "page3_declaration_treating_doctor_registration_number": "KMC-12345/KA",
    "page3_declaration_doctor_name": "Dr. Anand Krishnamurthy",
    "page3_declaration_doctor_qualification": "MS (General Surgery)",
    "page3_declaration_doctor_registration_number": "KMC-12345/KA",
    "hospital_declaration_treating_doctor_name": "Dr. Anand Krishnamurthy",
    "hospital_declaration_qualification": "MS (General Surgery)",
    "hospital_declaration_registration_number": "KMC-12345/KA",

    # Declaration - patient
    "patient_representative_name": "Rajesh Kumar Sharma",
    "patient_representative_contact_number": "9876543210",
    "patient_representative_email_id": "rajesh.sharma@email.com",
    "patient_representative_date": "15/03/2025",
    "patient_representative_time": "10:30",
    "patient_representative_signature": "Rajesh Kumar Sharma",
    "patient_declaration_name": "Rajesh Kumar Sharma",
    "patient_declaration_contact_number": "9876543210",
    "patient_declaration_email_id": "rajesh.sharma@email.com",
    "patient_declaration_signature": "Rajesh Kumar Sharma",
    "patient_declaration_date": "15/03/2025",
    "patient_declaration_time": "10:30",
    "patient_insured_name_declaration": "Rajesh Kumar Sharma",
    "patient_insured_contact_no_declaration": "9876543210",
    "patient_insured_email_id_declaration": "rajesh.sharma@email.com",
    "patient_insured_signature_declaration": "Rajesh Kumar Sharma",
    "patient_insured_date_declaration": "15/03/2025",
    "patient_insured_time_declaration": "10:30",
    "patient_insured_name_for_sign": "Rajesh Kumar Sharma",
    "patient_insured_name_for_signature": "Rajesh Kumar Sharma",
    "patient_insured_name_and_sign": "Rajesh Kumar Sharma",
    "patient_insured_name_and_sign_box": "Rajesh Kumar Sharma",
    "patient_insured_name_sign": "Rajesh Kumar Sharma",
    "patient_insured_name_signature": "Rajesh Kumar Sharma",
    "patient_insured_name_signature_name": "Rajesh Kumar Sharma",
    "patient_insured_name_signature_signature": "Rajesh Kumar Sharma",
    "patient_insured_name_declaration": "Rajesh Kumar Sharma",
    "declaration_patient_insured_name": "Rajesh Kumar Sharma",
    "declaration_patient_signature": "Rajesh Kumar Sharma",
    "declaration_patient_insured_name": "Rajesh Kumar Sharma",
    "declaration_patient_insured_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "declaration_patient_insured_contact_number": "9876543210",
    "declaration_patient_insured_signature": "Rajesh Kumar Sharma",
    "insured_name": "Rajesh Kumar Sharma",
    "insured_signature": "Rajesh Kumar Sharma",
    "insured_email_id": "rajesh.sharma@email.com",
    "insured_mobile_no": "9876543210",
    "patient_insured_name": "Rajesh Kumar Sharma",
    "patient_insured_contact_no": "9876543210",
    "patient_insured_signature": "Rajesh Kumar Sharma",
    "patient_insured_email_id": "rajesh.sharma@email.com",
    "patient_insured_date_d1": "1",
    "patient_insured_date_d2": "5",
    "patient_insured_date_m1": "0",
    "patient_insured_date_m2": "3",
    "patient_insured_date_y1": "2",
    "patient_insured_date_y2": "0",
    "patient_insured_date_y3": "2",
    "patient_insured_date_y4": "5",
    "patient_insured_time_h1": "1",
    "patient_insured_time_h2": "0",
    "patient_insured_time_m1": "3",
    "patient_insured_time_m2": "0",
    "patient_insured_contact_number_declaration": "9876543210",
    "patient_insured_contact_no": "9876543210",
    "patient_insured_contact_no_declaration": "9876543210",
    "patient_contact_number_declaration": "9876543210",
    "patient_email_id_declaration": "rajesh.sharma@email.com",
    "patient_email_id": "rajesh.sharma@email.com",
    "patient_insured_email_id_declaration": "rajesh.sharma@email.com",

    "page4_patient_insured_name": "Rajesh Kumar Sharma",
    "page4_patient_insured_contact_number": "9876543210",
    "page4_patient_insured_email_id": "rajesh.sharma@email.com",
    "page4_patient_insured_signature": "Rajesh Kumar Sharma",
    "page4_patient_insured_declaration_date": "15/03/2025",
    "page4_patient_insured_declaration_time": "10:30",
    "page4_patient_contact_number": "9876543210",
    "page4_patient_email_id": "rajesh.sharma@email.com",
    "page4_patient_insured_signature": "Rajesh Kumar Sharma",
    "page4_declaration_date": "15/03/2025",
    "page4_declaration_time": "10:30",
    "page4_patient_insured_name": "Rajesh Kumar Sharma",
    "page4_hospital_seal_box": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "page4_doctors_signature_box": "Dr. Anand Krishnamurthy",

    "patient_insured_name_sign_box": "Rajesh Kumar Sharma",
    "page3_hospital_seal_box": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "page3_patient_insured_name_sign_box": "Rajesh Kumar Sharma",

    # Hospital declaration
    "hospital_declaration_date": "15/03/2025",
    "hospital_declaration_time": "11:00",
    "hospital_date_declaration": "15/03/2025",
    "hospital_time_declaration": "11:00",
    "hospital_declaration_seal": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_declaration_doctor_signature": "Dr. Anand Krishnamurthy",
    "hospital_declaration_doctors_signature": "Dr. Anand Krishnamurthy",
    "hospital_declaration_doctors_signature_box": "Dr. Anand Krishnamurthy",
    "hospital_declaration_seal_box": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_seal": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_seal_box": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_seal_area": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_seal_area_declaration": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_declaration_hospital_seal": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_stamp_seal": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_declaration_signature": "Amrita Institute of Medical Sciences & Research Centre, Faridabad",
    "hospital_date_d1": "1",
    "hospital_date_d2": "5",
    "hospital_date_m1": "0",
    "hospital_date_m2": "3",
    "hospital_date_y1": "2",
    "hospital_date_y2": "0",
    "hospital_date_y3": "2",
    "hospital_date_y4": "5",
    "hospital_time_h1": "1",
    "hospital_time_h2": "1",
    "hospital_time_m1": "0",
    "hospital_time_m2": "0",
    "page4_hospital_declaration_date": "15/03/2025",
    "page4_hospital_declaration_time": "11:00",

    # Signatures
    "signature_treating_doctor": "Dr. Anand Krishnamurthy",
    "treating_doctor_signature": "Dr. Anand Krishnamurthy",
    "doctor_signature": "Dr. Anand Krishnamurthy",
    "doctor_signature_area": "Dr. Anand Krishnamurthy",
    "doctor_signature_name": "Dr. Anand Krishnamurthy",
    "doctor_signature_date": "15/03/2025",
    "doctor_signature_time": "11:00",
    "doctor_signature_hospital_declaration": "Dr. Anand Krishnamurthy",
    "signature_patient_insured": "Rajesh Kumar Sharma",
    "declaration_signature_insured": "Rajesh Kumar Sharma",
    "hospital_doctor_signature": "Dr. Anand Krishnamurthy",
    "doctors_signature_declaration": "Dr. Anand Krishnamurthy",

    # HDGC bank details
    "bank_account_pan": "ABCRS1234D",
    "bank_account_number": "1234567890",
    "bank_name_branch": "HDFC Bank, MG Road Branch, Bengaluru",
    "payable_details_cheque_dd": "NEFT",
    "bank_ifsc_code": "HDFC0001234",
    "bank_micr_no": "560240001",
    "declaration_date": "15/03/2025",
    "declaration_place": "Bengaluru",
    "declaration_time": "10:30",
    "hospital_declaration_place": "Bengaluru",

    # HDGC bill details
    "bill_no_1": "BILL-2025-001",
    "bill_date_1": "15/03/2025",
    "bill_issued_by_1": "Amrita Institute of Medical Sciences & Research Centre",
    "bill_towards_1": "Hospitalization charges",
    "bill_amount_1": "84500",
    "bill_no_2": "BILL-2025-002",
    "bill_date_2": "15/03/2025",
    "bill_issued_by_2": "Amrita Pharmacy",
    "bill_towards_2": "Medicines",
    "bill_amount_2": "10000",
    "bill_no_3": "BILL-2025-003",
    "bill_date_3": "15/03/2025",
    "bill_issued_by_3": "Amrita Diagnostics",
    "bill_towards_3": "Lab investigations",
    "bill_amount_3": "8000",
    "bill_no_4": "",
    "bill_date_4": "",
    "bill_issued_by_4": "",
    "bill_towards_4": "",
    "bill_amount_4": "",

    # HDGC checklist
    "checklist_duly_filled_claim_form": True,
    "checklist_copy_intimation_letter": True,
    "checklist_hospital_main_bill": True,
    "checklist_hospital_break_up_bill": True,
    "checklist_hospital_bill_payment_receipt": True,
    "checklist_hospital_discharge_summary": True,
    "checklist_pharmacy_bill": True,
    "checklist_operation_theater_notes": True,
    "checklist_ecg": True,
    "checklist_doctors_request_for_investigation": True,
    "checklist_doctors_prescription": True,
    "checklist_investigation_reports": True,
    "checklist_others_documents": True,
    "checklist_form_with_policy_number": True,
    "checklist_original_discharge_summary": True,
    "checklist_original_final_bill_payment_receipt": True,
    "checklist_original_investigation_reports": True,
    "checklist_neft_details_cancelled_cheque": True,
    "checklist_kyc_documents_for_1_lakh_plus": True,
    "checklist_all_original_bills_pharmacy_invoices": True,
    "checklist_implant_sticker_invoice": True,
    "checklist_past_treatment_documents": True,
    "checklist_accident_mlc_fir": True,
    "checklist_other_relevant_documents": True,
    "hospital_checklist_claim_form_filled": True,
    "hospital_checklist_original_pre_authorization_request": True,
    "hospital_checklist_copy_pre_authorization_approval_letter": True,
    "hospital_checklist_copy_photo_id_patient_verified": True,
    "hospital_checklist_hospital_discharge_summary": True,
    "hospital_checklist_operation_theatre_notes": True,
    "hospital_checklist_hospital_main_bill": True,
    "hospital_checklist_hospital_break_up_bill": True,
    "hospital_checklist_investigation_reports": True,
    "hospital_checklist_ct_mri_usg_hpe_report": True,
    "hospital_checklist_doctors_reference_slip_for_investigation": True,
    "hospital_checklist_ecg": True,
    "hospital_checklist_pharmacy_bills": True,
    "hospital_checklist_mlc_report_police_fir": True,
    "hospital_checklist_original_death_summary": True,
    "hospital_checklist_any_other_specify": True,
    "checklist_p6_duly_filled_claim_form": True,
    "checklist_p6_photocopy_id_current_year_policy": True,
    "checklist_p6_original_detailed_discharge_summary": True,
    "checklist_p6_original_consolidated_hospital_bill": True,
    "checklist_p6_original_payment_receipt_hospital_bill": True,
    "checklist_p6_first_consultation_letter_prescriptions": True,
    "checklist_p6_original_bills_payment_receipts_investigation_reports": True,
    "checklist_p6_original_medicine_bills_receipts_prescriptions": True,
    "checklist_p6_original_invoice_sticker_implants": True,
    "checklist_p6_copy_first_information_report_medico_legal_certificate": True,
    "checklist_p6_treating_doctors_certificate_injuries": True,
    "checklist_p6_copy_post_mortem_death_certificate": True,
    "checklist_p6_original_death_summary_hospital": True,
    "checklist_p6_copy_death_certificate_doctor_hospital_authority": True,
    "checklist_p6_copy_legal_heir_certificate": True,
    "checklist_p6_pre_post_duly_filled_claim_form": True,
    "checklist_p6_pre_post_photocopy_id_current_year_policy": True,
    "checklist_p6_pre_post_original_medicine_bills_prescriptions": True,
    "checklist_p6_pre_post_original_investigations_bills_reports": True,
    "checklist_p6_pre_post_original_consultation_bills_prescription": True,
    "checklist_p6_pre_post_copy_discharge_summary_main_claim": True,
    "checklist_p6_organ_function_blood_test_failure": True,
    "checklist_p6_treatment_certificate_transplant_surgeon": True,
    "checklist_p6_ambulance_duly_filled_claim_form": True,
    "checklist_p6_ambulance_photocopy_id_current_year_policy": True,
    "checklist_p6_ambulance_original_bill_payment_receipt": True,
    "checklist_p6_ambulance_treating_doctors_consultation_prescription": True,
    "kyc_legal_name_documents": True,
    "kyc_proof_of_residence_documents": True,

    # HDGC primary insured
    "primary_insured_policy_no": "POL-2024-78901",
    "primary_insured_sl_no_certificate_no": "CERT-2024-001",
    "primary_insured_company_tpa_id_no": "TPA-2024-00456",
    "primary_insured_name_surname": "Sharma",
    "primary_insured_name_firstname": "Rajesh",
    "primary_insured_name_middlename": "Kumar",
    "primary_insured_address_line1": "42, MG Road, Koramangala",
    "primary_insured_address_line2": "Bengaluru - 560034",
    "primary_insured_address_line3": "Karnataka",
    "primary_insured_city": "Bengaluru",
    "primary_insured_state": "Karnataka",
    "primary_insured_pin_code": "560034",
    "primary_insured_phone_no": "9876543210",
    "primary_insured_email_id": "rajesh.sharma@email.com",
    "first_insurance_commencement_date": "01/04/2022",

    # HDGC patient
    "patient_name_surname": "Sharma",
    "patient_name_firstname": "Rajesh",
    "patient_name_middlename": "Kumar",
    "patient_ip_registration_number": "IP-2025-001234",
    "patient_gender_male": True,
    "patient_gender_female": True,
    "patient_age": "45",
    "patient_dob": "15/03/1980",
    "patient_admission_date": "15/03/2025",
    "patient_admission_time": "10:30",
    "patient_discharge_date": "20/03/2025",
    "patient_discharge_time": "11:00",

    # ICICI ID proof
    "id_proof_aadhar_card": True,
    "id_proof_passport": True,
    "id_proof_driving_license": True,
    "id_proof_10th_class_certificate": True,
    "id_proof_others_checkbox": True,
    "id_proof_others_specify": "Voter ID",

    # ICICI
    "patient_mobile_no": "9876543210",
    "corporate_policy_no": "POL-2024-78901",
    "corporate_policy_name": "Infosys Group Health Policy",
    "hospital_fax_no": "080-26304051",
    "accident_rta_yes": True,
    "accident_rta_no": True,
    "accident_reported_to_police_yes": True,
    "accident_reported_to_police_no": True,
    "substance_abuse_injury_yes": True,
    "substance_abuse_injury_no": True,
    "substance_abuse_test_conducted_yes": True,
    "substance_abuse_test_conducted_no": True,
    "maternity_gravida": True,
    "maternity_para": True,
    "maternity_living": True,
    "maternity_abortion": True,
    "maternity_date_of_delivery": "N/A",
    "admission_time": "10:30",
    "expected_days_stay": "5",
    "per_day_room_rent_charges": "3500",
    "cost_investigation_diagnostics": "8000",
    "medicines_consumables_implants_other_expenses": "10000",
    "all_inclusive_package_charges": "0",
    "total_expected_cost_hospitalization": "84500",
    "declaration_patient_insured_name": "Rajesh Kumar Sharma",
    "declaration_patient_insured_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "declaration_patient_insured_contact_number": "9876543210",
    "declaration_patient_insured_signature": "Rajesh Kumar Sharma",
    "declaration_doctor_signature": "Dr. Anand Krishnamurthy",

    # PPN Declaration
    "ppn_hospital_name": "Amrita Institute of Medical Sciences & Research Centre",
    "ppn_hospital_address": "Mata Amritanandamayi Marg, Sector-88, Faridabad",
    "ppn_patient_name": "RAJESH KUMAR SHARMA",
    "ppn_age_sex": "45 / Male",
    "ppn_ip_no": "IP-2025-001234",
    "ppn_uhid_no": "UHID-2025-001234",
    "ppn_mobile_no": "9876543210",
    "ppn_date_of_admission": "15/03/2025",
    "ppn_time_of_admission": "10:30",
    "ppn_date_of_discharge": "20/03/2025",
    "ppn_time_of_discharge": "11:00",
    "ppn_id_proof": "42, MG Road, Koramangala, Bengaluru - 560034 (Aadhaar: 1234-5678-9012)",
    "ppn_attendant_name": "Priya Sharma",
    "ppn_attendant_mobile": "9876543211",
    "ppn_attendant_address": "42, MG Road, Koramangala, Bengaluru - 560034",
    "ppn_policy_number": "POL-2024-78901",
    "ppn_insurance_company": "Bajaj Allianz General Insurance",
    "ppn_additional_facility": "Laparoscopic Appendectomy - Surgical Package",
    "ppn_cost_amount": "84500",
    "ppn_cost_words": "Eighty Four Thousand Five Hundred Rupees Only",

    # Attendant
    "patient_attendant_name": "Priya Sharma",
    "patient_attendant_contact_no": "9876543211",
    "patient_attendant_mobile_no": "9876543211",
}

# ── Forms to generate ──────────────────────────────────────────────────────
FORMS = [
    "Ericson TPA Preauth",
    "BAJAJ ALLIANZ TPA PREAUTH FORM",
    "Care Health  PRE AUTH",
    "Chola-MS-Pre-Authorisation-Form",
    "East West TPA",
    "FHPL TPA",
    "FUTURE GENERLI pre auth",
    "Genins TPA Pre-Auth form",
    "GO DIGIT PREAUTH",
    "GOOD HEALTH TPA PREAUTH INS. FOAM",
    "HDFC",
    "HDGC CLAIM FORM A & B PART",
    "Health India Pre-Auth",
    "Health Insurance",
    "Heritage-Health-Pre-Auth-Form",
    "ICICI LOMBARD",
    "LIBERTY  Request Form",
    "Med-Save Pre-Auth",
    "Medi-assist TPA",
    "NIVA-BUPA",
    "Paramount TPA",
    "PPN_DECELARATION",
    "RAKSHA TPA PREAUTH",
    "Aditya Birla",
]

def generate_for_form(form_name):
    schema_path = ANALYZED_DIR / f"{form_name}.json"
    if not schema_path.exists():
        print(f"  SKIP: Schema not found for '{form_name}'")
        return

    with open(schema_path, "r", encoding="utf-8") as f:
        schema = json.load(f)

    fields = schema.get("fields", [])
    test_data = {}

    for field in fields:
        field_id = field.get("field_id")
        field_type = field.get("type", "text_line")
        if not field_id:
            continue

        if field_id in P:
            test_data[field_id] = P[field_id]
        elif field_type == "checkbox":
            test_data[field_id] = True
        elif field_type == "date_field":
            test_data[field_id] = "15/03/2025"
        else:
            test_data[field_id] = f"[{field_id}]"

    out_path = TEST_DATA_DIR / f"{form_name}_test_data.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(test_data, f, indent=2, ensure_ascii=False)

    print(f"  OK: {form_name} -> {len(test_data)} fields -> {out_path.name}")


if __name__ == "__main__":
    print("=" * 60)
    print("GENERATING REALISTIC TEST DATA FOR ALL FORMS")
    print("Patient: Rajesh Kumar Sharma | Acute Appendicitis | Surgical")
    print("=" * 60)
    for form in FORMS:
        generate_for_form(form)
    print("\nDone. All test data files generated in test_data/")
